"""Generate precomputed waveform peaks for every MP3 in audio/.

WaveSurfer can draw a waveform from these peaks instantly, so visitors only
download an MP3 when they actually press play.

Re-run this whenever you add or replace a track (requires ffmpeg + numpy):

    python3 tools/generate_peaks.py
"""
import json
import subprocess
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
AUDIO_DIR = ROOT / "audio"
OUTPUT = AUDIO_DIR / "peaks.js"
SAMPLE_RATE = 8000
NUM_PEAKS = 800


def compute_peaks(path):
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(path), "-ac", "1", "-ar", str(SAMPLE_RATE), "-f", "f32le", "-"],
        check=True,
        capture_output=True,
    ).stdout
    samples = np.abs(np.frombuffer(raw, dtype=np.float32))
    duration = len(samples) / SAMPLE_RATE
    buckets = np.array_split(samples, NUM_PEAKS)
    peaks = [round(float(b.max()) if len(b) else 0.0, 3) for b in buckets]
    return {"duration": round(duration, 3), "peaks": peaks}


def main():
    data = {}
    for path in sorted(AUDIO_DIR.glob("*.mp3")):
        print(f"Processing {path.name}")
        data[f"audio/{path.name}"] = compute_peaks(path)

    OUTPUT.write_text(
        "// Generated by tools/generate_peaks.py - do not edit by hand.\n"
        f"window.AUDIO_PEAKS = {json.dumps(data, separators=(',', ':'))};\n"
    )
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
